version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-php
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    depends_on:
      - mysql

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    depends_on:
      - php

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: laravel-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data: